apiVersion: apps/v1
kind: Deployment
metadata:
  name: modernapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: modernapi
  template:
    metadata:
      labels:
        app: modernapi
    spec:
      containers:
        - name: modernapi
          image: modernapi:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: modernapi-config
            - secretRef:
                name: modernapi-secrets
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5